[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 3000

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = ".netlify/functions"

# Environment variables para produção
[context.production.environment]
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_live_51PcM6UFuXE24kn9Z7LlT1OFU8VYq6tlC9xr7gvBBghNIU2tBDvmXoGhw6CyBbd6pNNxX1tukbitK8ze73zphX5NU00gzrEepVS"
  STRIPE_SECRET_KEY = "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"
  NEXT_PUBLIC_RAMP_API_KEY = "YOUR_RAMP_API_KEY"

# Redirects para SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers para performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
